apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: exam-robindehullu
  labels:
    createdBy: "Robin-Dehullu"

spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: nathansegers/containers_23-24_december_frontend
          name: frontend-demo
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: exam-robindehullu
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
